version: '3'

services:
  skystream:
    image: 'ghcr.io/deathbymisadventure/sierra-axe:latest'
    container_name: sierra-axe
    ports:
      - 1935:1935
      - 80:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - RTMP_FRAG_SIZE=2s
      - RTMP_PLAYLIST_LENGTH=10s
      - STREAM_APP_NAME=stream
    restart: always

    