services:
  sierraaxe:
    image: ghcr.io/deathbymisadventure/sierraaxe:latest
    container_name: sierra-axe
    pull_policy: always
    ports:
      - 1935:1935
      - 80:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - RTMP_FRAG_SIZE=2s
      - RTMP_PLAYLIST_LENGTH=10s
      - STREAM_APP_NAME=stream
    restart: always
