apiVersion: apps/v1
kind: Deployment
metadata:
  name: sierra-axe
  labels:
    app: sierra-axe
spec:
  selector:
    matchLabels:
      app: sierra-axe
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sierra-axe
    spec:
      containers:
        - name: sierra-axe
          resources: {}
          image: ghcr.io/deathbymisadventure/sierraaxe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: HTTP_PORT
              value: '80'
            - name: RTMP_FRAG_SIZE
              value: 2s
            - name: RTMP_PLAYLIST_LENGTH
              value: 10s
            - name: RTMP_PORT
              value: '1935'
            - name: STREAM_APP_NAME
              value: stream
          livenessProbe:
            httpGet:
              host: ''
              path: /stat
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sierra-axe-service
  name: sierra-axe-service
spec:
  ports:
    - name: rmtp
      port: 1935
      targetPort: 1935
      nodePort: 31935
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: sierra-axe
  type: NodePort
