apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sierra-axe.fullname" . }}-configmap
  labels:
    app: sierra-axe
  {{- include "sierra-axe.labels" . | nindent 4 }}
data:
  HTTP_PORT: {{ quote .Values.sierraAxe.httpPort }}
  RTMP_FRAG_SIZE: {{ quote .Values.sierraAxe.rtmpFragSize }}
  RTMP_PLAYLIST_LENGTH: {{ quote .Values.sierraAxe.rtmpPlaylistLength }}
  RTMP_PORT: {{ quote .Values.sierraAxe.rtmpPort }}
  STREAM_APP_NAME: {{ quote .Values.sierraAxe.streamAppName }}
