apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sierra-axe.fullname" . }}-deployment
  labels:
    app: sierra-axe
  {{- include "sierra-axe.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sierra-axe
    {{- include "sierra-axe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sierra-axe
      {{- include "sierra-axe.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: sierra-axe
        image: {{ .Values.sierraAxe.image.repository }}:{{ .Values.sierraAxe.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.sierraAxe.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "sierra-axe.fullname" . }}-configmap
        readinessProbe:
          httpGet:
            path: /stat
            port: {{ .Values.sierraAxe.httpPort }}
        livenessProbe:
          httpGet:
            path: /stat
            port: {{ .Values.sierraAxe.httpPort }}
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: {{ .Values.sierraAxe.rtmpPort }}
          name: rtmp
          protocol: TCP
        - containerPort: {{ .Values.sierraAxe.httpPort }}
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.sierraAxe.resources | nindent 10 }}
