apiVersion: v1
kind: Service
metadata:
  name: {{ include "sierra-axe.fullname" . }}-service
  labels:
    name: sierra-axe-service
  {{- include "sierra-axe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sierra-axe
    {{- include "sierra-axe.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
