apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\chad.amberg\Downloads\kompose-windows-amd64.exe convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: skystream
  name: skystream
spec:
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: http
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: skystream
  type: NodePort
status:
  loadBalancer: {}
