apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\chad.amberg\Downloads\kompose-windows-amd64.exe convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: skystream
  name: skystream
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: skystream
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\chad.amberg\Downloads\kompose-windows-amd64.exe convert -c
        kompose.service.expose: "true"
        kompose.service.type: nodeport
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: skystream
    spec:
      containers:
        - env:
            - name: HTTP_PORT
              value: 80
            - name: RTMP_FRAG_SIZE
              value: 2s
            - name: RTMP_PLAYLIST_LENGTH
              value: 10s
            - name: RTMP_PORT
              value: 1935
            - name: STREAM_APP_NAME
              value: stream
          image: skystream
          name: skystream
          ports:
            - containerPort: 1935
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
