---
# Source: sierra-axe/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-sierra-axe-configmap
  labels:
    app: sierra-axe
    helm.sh/chart: sierra-axe-0.1.0
    app.kubernetes.io/name: sierra-axe
    app.kubernetes.io/instance: sa
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
data:
  HTTP_PORT: "80"
  RTMP_FRAG_SIZE: "2s"
  RTMP_PLAYLIST_LENGTH: "10s"
  RTMP_PORT: "1935"
  STREAM_APP_NAME: "stream"
---
# Source: sierra-axe/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sa-sierra-axe-service
  labels:
    name: sierra-axe-service
    helm.sh/chart: sierra-axe-0.1.0
    app.kubernetes.io/name: sierra-axe
    app.kubernetes.io/instance: sa
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  selector:
    app: sierra-axe
    app.kubernetes.io/name: sierra-axe
    app.kubernetes.io/instance: sa
  ports:
  - name: rmtp
    nodePort: 31935
    port: 1935
    targetPort: 1935
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
---
# Source: sierra-axe/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-sierra-axe-deployment
  labels:
    app: sierra-axe
    helm.sh/chart: sierra-axe-0.1.0
    app.kubernetes.io/name: sierra-axe
    app.kubernetes.io/instance: sa
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sierra-axe
      app.kubernetes.io/name: sierra-axe
      app.kubernetes.io/instance: sa
  template:
    metadata:
      labels:
        app: sierra-axe
        app.kubernetes.io/name: sierra-axe
        app.kubernetes.io/instance: sa
    spec:
      containers:
      - name: sierra-axe
        image: ghcr.io/deathbymisadventure/sierraaxe:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: sa-sierra-axe-configmap
        readinessProbe:
          httpGet:
            path: /stat
            port: 80
        livenessProbe:
          httpGet:
            path: /stat
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 30
        ports:
        - containerPort: 1935
          name: rtmp
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
