service:
  # -- Service ports including HTTP and RTMP
  ports:
  - name: rmtp
    nodePort: 31935
    port: 1935
    targetPort: 1935
  - name: http
    nodePort: 30080
    port: 80
    targetPort: 80
  # -- Service type
  type: LoadBalancer
sierraAxe:
  # -- HTTP published port
  httpPort: "80"
  # -- RTMP Tuning: Fragment Size
  rtmpFragSize: 2s
  # -- RTMP Tuning: Playlist Length
  rtmpPlaylistLength: 10s
  # -- RTMP published port
  rtmpPort: "1935"
  # -- RTPM stream name to publish
  streamAppName: stream
  # -- Image information
  image:
    repository: ghcr.io/deathbymisadventure/sierraaxe
    tag: latest
  # -- Image pull policy
  imagePullPolicy: IfNotPresent
  # -- Pod assigned resources
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi